# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/recherche/projets/WaveComputer/dev/synthesis/constraints/io_constraints.xdc

# Block Designs: bd/design_QB/design_QB.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_QB || ORIG_REF_NAME==design_QB} -quiet] -quiet

# IP: bd/design_QB/ip/design_QB_processing_system7_0_0/design_QB_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_QB_processing_system7_0_0 || ORIG_REF_NAME==design_QB_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_QB/ip/design_QB_proc_sys_reset_0_0/design_QB_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_QB_proc_sys_reset_0_0 || ORIG_REF_NAME==design_QB_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_QB/ip/design_QB_PL_top_level_0_0/design_QB_PL_top_level_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_QB_PL_top_level_0_0 || ORIG_REF_NAME==design_QB_PL_top_level_0_0} -quiet] -quiet

# XDC: bd/design_QB/design_QB_ooc.xdc
